checkpoint: /home/it/Data/thaiphData/image-compression-with-autoencoders/cae/model_yt_small_final.state
exp_name: testing
batch_every: 100
shuffle: false
dataset_path: /home/it/Data/thaiphData/image-compression-with-autoencoders/cae/datasets/testing
num_workers: 1
device: cuda
